### ISSUE TITLE
Performance with respect to graph scale 

### ISSUE THREAD

**Issue by arita37** [microsoft/causica#13]
Hello,

Just wodnering if the training can handle 
up to 1 million nodes ? or rather 100k nodes ?

Just wondering if there is any scientific methods to reduce the size of the graph ? (ie KMeans aggregation…, wont it create additional issues, co-cofounder merging), what about distance ?

Sorry for many questions, thanks

**Comment by LaurantChao** [comment]
Hi, thanks for your interest in our code base. Current we have not tested our training on such large scale of nodes, and 100k nodes is far larger than we have handled before (previously our scale is ~1k-ish nodes). Generally our code support the so-called grouping strategy to reduce the size, which groups similar variables into one node (you can think of it as a vector-valued node) instead of naively merging the nodes. However I doubt how useful this would be considering the scale of your problem.

**Comment by LaurantChao** [comment]
Thanks for the clarification. If you are referring to the number of dataset samples, then  yes, in terms of training our method can scale to 1 million data points. Note that this depends on the dimensionality of each data points as well.

Meanwhile, the inference for ITEs might be a bit more challenging. As for casual inference, our method requires generating a lot of interventional samples for each data point in the test set. Therefore if your test set also has 1 million data points, it will be quite slow. If you are only estimating population effects, e.g., ATEs then this should be fine.


Thanks,
Chao
