### ISSUE TITLE
Optimization of interventions

### ISSUE THREAD

**Issue by fkgruber** [microsoft/causica#38]
Hi
Once we have our models and we have determined the important causal drivers of our outcome, we may want to determine the optimal set of interventions. I imagine that this is the step 6 in your diagram:
![image](https://user-images.githubusercontent.com/4311763/227782203-cbaf77f0-3dc3-4e8a-98a0-abd6866b5750.png)

However, in your paper I don't see any details on this step. Given the nonlinearity of your models I imagine there are interaction effects (in sense that the effect of X2 on the endpoint may change with the value of X1) as opposed of the effects being entirely additive. Therefore, we can't optimize on the interventions of multiple variables independently, they need to be jointly optimized. 

Does your framework has a way to optimize the interventions of  multiple variables efficiently? How would you determine whether there is an interaction effect?
thanks
FKG

**Comment by confoundry** [comment]
Hi @fkgruber,

I assume you have a known set of continuous treatment nodes and a continuous treatment effect node that you're interested in. In this case you need to pick a metric to optimise, ATE is probably a good place to start. There is no analytic way to do this for a general non-linear model, so you'll have to estimate it by sampling.

The SEM class doesn't currently have an `rsample` [method]( https://pytorch.org/docs/stable/distributions.html#torch.distributions.distribution.Distribution.rsample), but you could add one by copying the `sample` method and replacing the `sample` calls with `rsample` ones. Both of the continuous noise distributions (spline and gaussian) have `rsample` methods.

You can then maximise the monte carlo estimate of the ATE wrt the treatments, since the gradients will flow through `rsample`.

To estimate the interaction effects, you can calculate the CATE, conditioning on different values of X1. General CATEs aren't supported by this version of the model, but for root nodes like X1, interventions and conditioning are equivalent.
