### ISSUE TITLE
Constraint derived from calculate_dagness() is infinity

### ISSUE THREAD

**Issue by jiayang97** [microsoft/causica#67]
Hi, I am using causica0.2.0 on the Diabetes data set from the BN Learn repository. It has 10k samples, 413 nodes, 602 edges and contains mixed data.

During the first backward prop, I get the error "nan values found" due to the constraint generated from calculate_dagness() function being infinity. I have played around with the following parameters to try and fix the issue but to no avail:

    class TrainingConfig:
        noise_dist: ContinuousNoiseDist = ContinuousNoiseDist.GAUSSIAN
        batch_size: int = 100
        max_epoch: int = 1 
        gumbel_temp: float = 0.5
        averaging_period: int = 100
        prior_sparsity_lambda: float = 0
        init_rho: float = 0
        init_alpha: float = 0

    training_config = TrainingConfig()
    auglag_config = AugLagLRConfig(lr_init_dict={"vardist": 1e-3, "icgnn": 3e-4, "noise_dist": 3e-3})

Do let me know if there's anything I can do to fix this issue, thanks so much :) !

**Comment by confoundry** [comment]
Hi @jiayang97,

The problem is that `calculate_dagness` calculates the matrix exponential, which with 413 nodes and reasonably connected graph is going to overflow. We are working on introducing the dagness penalty more slowly, by approximating the matrix exponential with truncated power series.

To fix the NaN's for now, you could schedule the addition of the dagness term, so that it is not calculated early in the learning procedure, but is added later. You will, however, find that with so many nodes the calculation of the exponential is very slow.

**Comment by jiayang97** [comment]
Hi Sir/Mdm,

Thanks for taking your time to reply, I look forward to the new approach you are planning to introduce in the future package. In the meantime, I will try the latter approach. Thanks again :)
